### ISSUE TITLE
suggestion: adding tags to the resource and search bar

### ISSUE THREAD

**Issue by CiTRuS93** [Parasgupta44/ml-resources-react#5] opened 2020-09-30 12:25 UTC
tags like programming language etc...

**Comment by Parasgupta44** [comment] 2020-09-30 12:38
> tags like programming language etc...

These can be some really nice features for sure!

**Comment by CiTRuS93** [comment] 2020-09-30 13:19
great!
can you assign it to me?

**Comment by Parasgupta44** [comment] 2020-09-30 13:50
> great!
> can you assign it to me?

Sure, done....thanks!

**Comment by CiTRuS93** [comment] 2020-10-01 07:53
hey @Parasgupta44! I'm want to use a search icon for the search bar,
where should I put it?

**Comment by Parasgupta44** [comment] 2020-10-01 08:00
> hey @Parasgupta44! I'm want to use a search icon for the search bar,
> where should I put it?

Maybe we can shift the heading to float left and can put the search thingy on right...
Also...you can pull the latest changes from the master...I have been merging pull requests for various things !!

**Comment by CiTRuS93** [comment] 2020-10-01 08:10
how about this:
![image](https://user-images.githubusercontent.com/13310488/94784322-a8836480-03d6-11eb-8af1-13586be949c7.png)


![image](https://user-images.githubusercontent.com/13310488/94784279-999cb200-03d6-11eb-8065-3367492ddea2.png)

**Comment by Parasgupta44** [comment] 2020-10-01 08:11
This looks pretty awesome !!
Thanks.

**Comment by Parasgupta44** [comment] 2020-10-01 09:06
Thanks @CiTRuS93  for the feature..
I just checked search is case sensitive...can you look into it once you get the time and do a PR ?
(I have merged the previous changes.)

**Comment by CiTRuS93** [comment] 2020-10-01 09:13
sure, I'm on it

**Comment by Parasgupta44** [comment] 2020-10-01 09:17
> sure, I'm on it

Merged...thanks for such a quick response !!

**Comment by kartikmandhan** [comment] 2020-10-01 11:22
hey, I can improve the styling and animations of the search box, but the problem is that i can't see the code of the search box when i clone the repo, while I can see search bar on the website on netlify.app website. why is it so?

**Comment by CiTRuS93** [comment] 2020-10-01 11:35
@kartikmandhan  it's in Display.jsx line 14

**Comment by kartikmandhan** [comment] 2020-10-01 12:07
@CiTRuS93 thanks buddy

**Closed as completed** 2020-10-03 10:49 UTC
Labels: enhancement, help wanted, good first issue, hacktoberfest
